-- generated by tools/seed-from-prototype.mjs. Do not hand-edit.
-- Reference content for every environment. No media_assets are seeded here.

INSERT INTO site_settings (id, org_name_ar, org_name_en, tagline_ar, tagline_en, footer_blurb_ar, footer_blurb_en, rights_line_ar, rights_line_en, phone, email, address_ar, address_en, facebook_url, instagram_url, x_url, en_enabled, seo_title_ar, seo_title_en, seo_description_ar, seo_description_en, notify_email_on_status_change, notify_sms_on_status_change, application_ref_prefix, updated_by) VALUES
  (1, 'جمعية سفير الدعوية', 'Safeer Da\'wah Association', 'لطلاب المنح', 'For scholarship students', 'جمعية أهلية غير ربحية متخصصة في رعاية طلاب وطالبات المنح الدوليين الدارسين في الجامعات السعودية.', 'A Saudi non-profit association dedicated to supporting international scholarship students at Saudi universities.', 'جميع الحقوق محفوظة لجمعية سفير بالمملكة العربية السعودية', 'All rights reserved — Safeer Association, Saudi Arabia', '+966 53 464 6648', 'info@safeer-sa.org', 'الرياض — حي السويدي، شارع سدير، المملكة العربية السعودية', 'Riyadh — Al Suwaidi, Sudair St., Kingdom of Saudi Arabia', NULL, NULL, NULL, 1, 'جمعية سفير الدعوية', 'Safeer Da\'wah Association', 'جمعية أهلية غير ربحية متخصصة في رعاية طلاب وطالبات المنح الدوليين الدارسين في الجامعات السعودية.', 'A Saudi non-profit association dedicated to supporting international scholarship students at Saudi universities.', 1, 1, 'SA', NULL);

INSERT INTO pages (slug, title_ar, title_en, meta_title_ar, meta_title_en, meta_description_ar, meta_description_en, is_published, needs_review) VALUES
  ('home', 'الرئيسية', 'Home', 'الرئيسية', 'Home', 'جمعية أهلية غير ربحية متخصصة في رعاية طلاب وطالبات المنح الدوليين الدارسين في الجامعات السعودية.', 'A Saudi non-profit association dedicated to supporting international scholarship students at Saudi universities.', 1, 0),
  ('about', 'من نحن', 'About us', 'من نحن', 'About us', 'جمعية أهلية غير ربحية متخصصة في رعاية طلاب وطالبات المنح الدوليين الدارسين في الجامعات السعودية.', 'A Saudi non-profit association dedicated to supporting international scholarship students at Saudi universities.', 1, 0),
  ('board', 'مجلس الإدارة', 'Board of directors', 'مجلس الإدارة', 'Board of directors', 'المجلس المسؤول عن حوكمة الجمعية واعتماد خططها وبرامجها.', 'The body responsible for governance and for approving the association\'s plans and programmes.', 1, 0),
  ('work', 'مجالات عمل الجمعية', 'Our areas of work', 'مجالات عمل الجمعية', 'Our areas of work', 'تهدف الجمعية إلى نشر التعاليم الإسلامية وتعزيز القيم الدينية، وتعمل في أربعة مجالات رئيسية.', 'The association works to share Islamic teachings and strengthen religious values across four main areas.', 1, 0),
  ('scholarships', 'منح الوافدين للدراسة بالجامعات السعودية', 'Scholarships for international students in Saudi universities', 'منح الوافدين للدراسة بالجامعات السعودية', 'Scholarships for international students in Saudi universities', 'تلعب الجمعية دوراً محورياً في رعاية طلاب المنح الدوليين، عبر دعم شامل يسهّل تكيّفهم ويعزّز تجربتهم الأكاديمية والثقافية.', 'The association plays a central role in caring for international scholarship students, with support that eases adaptation and enriches their academic and cultural experience.', 1, 0),
  ('news', 'أخبار الجمعية', 'Association news', 'أخبار الجمعية', 'Association news', 'أنشطة وفعاليات ومحاضر اجتماعات — بتصنيفات عربية تخص عمل الجمعية.', 'Activities, events and meeting minutes — with categories that match the association\'s actual work.', 1, 0),
  ('article', 'مقال إخباري', 'News article', 'مقال إخباري', 'News article', NULL, NULL, 1, 0),
  ('testimonials', 'قالوا عنا', 'What people say', 'قالوا عنا', 'What people say', 'آراء المستفيدين كما وصلتنا — الإيجابي منها والمقترحات على حد سواء.', 'Beneficiary feedback as we received it — the praise and the suggestions alike.', 1, 0),
  ('partners', 'شركاء النجاح', 'Our partners', 'شركاء النجاح', 'Our partners', 'الجهات التي نعمل معها في رعاية طلاب المنح وتنفيذ البرامج الدعوية والتدريبية.', 'The organisations we work with on student care, outreach and training.', 1, 0),
  ('documents', 'التراخيص والسياسات واللوائح', 'Licences, policies and regulations', 'التراخيص والسياسات واللوائح', 'Licences, policies and regulations', 'مستندات الجمعية الرسمية في مكان واحد — بمعاينة مباشرة وتحميل.', 'Official documents in one place — with previews and downloads.', 1, 0),
  ('contact', 'تواصل معنا', 'Contact us', 'تواصل معنا', 'Contact us', 'إذا كانت لديك أي أسئلة أو كنت بحاجة إلى مساعدة، فلا تتردد في الاتصال بنا.', 'If you have a question or need help, get in touch.', 1, 0);

-- page_sections: the home page's 9 sections, in prototype order (partners hidden)

INSERT INTO page_sections (page_id, section_key, label_ar, label_en, heading_ar, heading_en, body_ar, body_en, primary_button_label_ar, primary_button_label_en, primary_button_url, secondary_button_label_ar, secondary_button_label_en, secondary_button_url, image_asset_id, is_published, sort_order) VALUES
  ((SELECT id FROM pages WHERE slug = 'home'), 'hero', 'الواجهة الرئيسية', 'Hero', 'نرعى طلاب المنح ونبني جسور المعرفة', 'We care for scholarship students and build bridges', 'دعم أكاديمي ونفسي وإرشاد ديني وتمكين مجتمعي لطلاب وطالبات المنح الدوليين الدارسين في الجامعات السعودية.', 'Academic and psychological support, religious guidance and community empowerment for international scholarship students at Saudi universities.', 'قدّم طلب منحة', 'Apply for a scholarship', '#/apply', 'تعرّف على الجمعية', 'About the association', '#/about', NULL, 1, 0),
  ((SELECT id FROM pages WHERE slug = 'home'), 'about', 'من نحن', 'About', 'الرؤية والرسالة والأهداف', 'Vision, mission and goals', NULL, NULL, 'اقرأ المزيد عن الجمعية', 'Read more about us', '#/about', NULL, NULL, NULL, NULL, 1, 1),
  ((SELECT id FROM pages WHERE slug = 'home'), 'impact', 'أثرنا', 'Our impact', 'بالأرقام', 'In numbers', 'تُحرَّر هذه الأرقام من لوحة التحكم — ولا تُنشر إلا بأرقام موثقة.', 'Edited from the dashboard — published only once verified.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 2),
  ((SELECT id FROM pages WHERE slug = 'home'), 'work_areas', 'مجالات عملنا', 'Our work', 'أربعة مجالات، هدف واحد', 'Four areas, one purpose', NULL, NULL, NULL, NULL, NULL, 'كل المجالات', 'All areas', '#/work', NULL, 1, 3),
  ((SELECT id FROM pages WHERE slug = 'home'), 'student_care', 'منح الوافدين', 'Scholarships', 'رعاية متكاملة لطالب المنحة', 'Complete care for a scholarship student', 'من لحظة الوصول إلى التخرج: دعم يسهّل التكيّف مع البيئة الجديدة ويعزّز التجربة الأكاديمية والثقافية.', 'From arrival to graduation: support that eases adaptation and strengthens the academic and cultural experience.', 'تفاصيل برنامج المنح', 'Scholarship programme details', '#/scholarships', NULL, NULL, NULL, NULL, 1, 4),
  ((SELECT id FROM pages WHERE slug = 'home'), 'news', 'أخبارنا', 'News', 'آخر الأنشطة', 'Latest activity', NULL, NULL, NULL, NULL, NULL, 'كل الأخبار', 'All news', '#/news', NULL, 1, 5),
  ((SELECT id FROM pages WHERE slug = 'home'), 'testimonials', 'قالوا عنا', 'Testimonials', 'ما يقوله المستفيدون', 'What beneficiaries say', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 6),
  ((SELECT id FROM pages WHERE slug = 'home'), 'partners', 'شركاء النجاح', 'Partners', 'من نعمل معهم', 'Who we work with', NULL, NULL, NULL, NULL, NULL, 'مشاهدة كل الشركاء', 'See all partners', '#/partners', NULL, 0, 7),
  ((SELECT id FROM pages WHERE slug = 'home'), 'cta', 'دعوة للتسجيل', 'Call to action', 'للتسجيل في جمعية سفير الدعوية', 'Register with Safeer Association', 'قدّم طلبك إلكترونياً وتابع حالته من بوابة الطالب دون مراجعة المقر.', 'Apply online and follow your application in the student portal — no office visit needed.', 'تسجيل طلب منحة', 'Apply now', '#/apply', 'تواصل معنا', 'Contact us', '#/contact', NULL, 1, 8);

-- about_items: vision + mission, 5 goals, 4 care pillars, 5 scholarship steps, 4 requirements

INSERT INTO about_items (kind, icon, title_ar, title_en, body_ar, body_en, is_published, sort_order) VALUES
  ('vision', 'eye', 'الرؤية', 'Vision', 'الريادة في الدعوة المتخصصة باستخدام التقنية الحديثة، ورعاية طلاب المنح في الجامعات السعودية.', 'Leadership in specialised outreach using modern technology, and care for scholarship students at Saudi universities.', 1, 0),
  ('mission', 'msg', 'الرسالة', 'Mission', 'تقديم خدمات دعوية وتعليمية وإرشادية نوعية تُعرّف بالإسلام، وتدعم الطالب الوافد أكاديمياً ونفسياً ومجتمعياً.', 'Delivering quality outreach, education and guidance that introduce Islam and support incoming students academically, psychologically and socially.', 1, 0),
  ('goal', NULL, 'استخدام التقنية الحديثة في الدعوة إلى الله ونشر العلم الشرعي', 'Using modern technology in outreach and in spreading religious knowledge', NULL, NULL, 1, 0),
  ('goal', NULL, 'تصحيح المفاهيم المغلوطة عن الإسلام ورد الشبهات المثارة عليه', 'Correcting misconceptions about Islam and answering claims raised against it', NULL, NULL, 1, 1),
  ('goal', NULL, 'تعليم المسلمين أصول دينهم وتعميق روابط الأخوة فيما بينهم', 'Teaching Muslims the fundamentals of their faith and deepening bonds between them', NULL, NULL, 1, 2),
  ('goal', NULL, 'الدعوة المتخصصة للفئات الاجتماعية', 'Specialised outreach for specific social groups', NULL, NULL, 1, 3),
  ('goal', NULL, 'الاهتمام الدعوي بالجاليات والتواصل معهم', 'Engaging with and supporting expatriate communities', NULL, NULL, 1, 4),
  ('care_pillar', 'book', 'الدعم الأكاديمي والتعليمي', 'Academic and educational support', 'دورات تعليم اللغة العربية لغير الناطقين بها، ودروس تقوية في المواد الأكاديمية، ومرشدون أكاديميون للمناهج والبحوث والمشاريع.', 'Arabic courses for non-native speakers, tutoring in academic subjects, and academic mentors for curricula, research and projects.', 1, 0),
  ('care_pillar', 'heart', 'الدعم النفسي والإرشادي', 'Psychological and counselling support', 'مستشارون متخصصون، وجلسات توعية وورش عمل حول مهارات التكيّف وإدارة الضغوط بعيداً عن الأهل والوطن.', 'Specialist counsellors, awareness sessions and workshops on adapting and managing pressure far from home.', 1, 1),
  ('care_pillar', 'mosque', 'الإرشاد الديني والدعوي', 'Religious guidance', 'دروس في الفقه والشريعة، ولقاءات دعوية، وتيسير أداء الفرائض وتنظيم رحلات العمرة والزيارة.', 'Classes in jurisprudence and Shari\'ah, outreach gatherings, prayer facilities and organised Umrah trips.', 1, 2),
  ('care_pillar', 'people', 'التمكين والمشاركة المجتمعية', 'Empowerment and community participation', 'تشجيع الطلاب على الأنشطة التطوعية وخدمة المجتمع السعودي، بما يعزّز شعور الانتماء والاندماج.', 'Encouraging students into volunteering and service to Saudi society, strengthening belonging and integration.', 1, 3),
  ('scholarship_step', NULL, 'تعبئة الطلب', 'Fill the form', 'بيانات شخصية وأكاديمية عبر نموذج من ثلاث خطوات.', 'Personal and academic details in a three-step form.', 1, 0),
  ('scholarship_step', NULL, 'رفع المستندات', 'Upload documents', 'صورة الهوية والشهادات الدراسية بصيغة PDF أو صورة.', 'ID copy and certificates as PDF or image.', 1, 1),
  ('scholarship_step', NULL, 'المراجعة الأولية', 'Initial review', 'تدقيق اكتمال البيانات والمستندات من فريق الجمعية.', 'The team checks the data and documents are complete.', 1, 2),
  ('scholarship_step', NULL, 'المقابلة', 'Interview', 'موعد يُحجز من البوابة عند اجتياز المراجعة.', 'Booked from the portal once review is passed.', 1, 3),
  ('scholarship_step', NULL, 'القرار والرعاية', 'Decision and care', 'إشعار بالقرار، ثم بدء برنامج الرعاية والمتابعة.', 'Decision notice, then the care programme begins.', 1, 4),
  ('requirement', NULL, 'صورة الهوية أو جواز السفر', 'ID or passport copy', NULL, NULL, 1, 0),
  ('requirement', NULL, 'الشهادات الدراسية', 'Academic certificates', NULL, NULL, 1, 1),
  ('requirement', NULL, 'اسم الجامعة والمرحلة الدراسية', 'University name and degree level', NULL, NULL, 1, 2),
  ('requirement', NULL, 'بريد إلكتروني ورقم هاتف فعّالان', 'A working email and phone number', NULL, NULL, 1, 3);

INSERT INTO stats (value, label_ar, label_en, sub_ar, sub_en, is_published, sort_order) VALUES
  (2, 'أعوام من الخبرة', 'Years of experience', NULL, NULL, 1, 0),
  (NULL, 'طالب وطالبة مستفيد', 'Students supported', NULL, NULL, 1, 1),
  (NULL, 'برنامج وفعالية', 'Programmes and events', NULL, NULL, 1, 2),
  (NULL, 'جهة شريكة', 'Partner organisations', NULL, NULL, 1, 3);

INSERT INTO work_areas (icon, title_ar, title_en, is_published, sort_order) VALUES
  ('mic', 'الدعوة العامة', 'General outreach', 1, 0),
  ('globe', 'الدعوة الإلكترونية', 'Digital outreach', 1, 1),
  ('cap', 'التدريب والتأهيل', 'Training and qualification', 1, 2),
  ('search', 'الأبحاث والدراسات الدعوية', 'Research and studies', 1, 3);

INSERT INTO work_area_items (work_area_id, text_ar, text_en, sort_order) VALUES
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة العامة'), 'الدعوة الشبابية والنسائية والجاليات', 'Youth, women and expatriate community outreach', 0),
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة العامة'), 'معرض الوسائل الدعوية', 'Outreach media exhibition', 1),
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة العامة'), 'المشاركات المجتمعية والمصليات المتنقلة', 'Community participation and mobile prayer spaces', 2),
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة العامة'), 'الحج والعمرة', 'Hajj and Umrah', 3),
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة الإلكترونية'), 'دعوة غير المسلمين', 'Outreach to non-Muslims', 0),
  ((SELECT id FROM work_areas WHERE title_ar = 'الدعوة الإلكترونية'), 'استخدام الوسائل الحديثة في الدعوة', 'Using modern channels for outreach', 1),
  ((SELECT id FROM work_areas WHERE title_ar = 'التدريب والتأهيل'), 'تأهيل الكوادر الإدارية', 'Qualifying administrative staff', 0),
  ((SELECT id FROM work_areas WHERE title_ar = 'التدريب والتأهيل'), 'تأهيل الدعاة — علمياً ومهارياً', 'Qualifying outreach workers — academically and practically', 1),
  ((SELECT id FROM work_areas WHERE title_ar = 'الأبحاث والدراسات الدعوية'), 'إعداد البحوث الشرعية', 'Producing religious research', 0),
  ((SELECT id FROM work_areas WHERE title_ar = 'الأبحاث والدراسات الدعوية'), 'المسابقات العامة', 'Public competitions', 1),
  ((SELECT id FROM work_areas WHERE title_ar = 'الأبحاث والدراسات الدعوية'), 'تطوير وصناعة المحتوى الدعوي', 'Developing outreach content', 2);

INSERT INTO board_members (name_ar, name_en, role_ar, role_en, grp, is_lead, photo_asset_id, is_published, sort_order) VALUES
  ('د. عبد الله بن دجين بن علي السهلي', 'Dr. Abdullah bin Dujain Al-Suhali', 'رئيس المجلس', 'Chairman', 'board', 1, NULL, 1, 0),
  ('د. فهد بن سعيد بن ناصر بن سعيد', 'Dr. Fahd bin Saeed bin Nasser', 'نائب الرئيس', 'Vice Chairman', 'board', 0, NULL, 1, 1),
  ('د. سالم بن عبد الله بن عامر العجمي', 'Dr. Salem bin Abdullah Al-Ajmi', 'مشرف مالي', 'Financial supervisor', 'board', 0, NULL, 1, 2),
  ('د. عبد الرحمن عبد الكريم البراهيم اليزيد', 'Dr. Abdulrahman Al-Ibrahim Al-Yazid', 'عضو', 'Member', 'board', 0, NULL, 1, 3),
  ('د. عثمان بن سليمان بن حمد العراجه', 'Dr. Othman bin Sulaiman Al-Arajah', 'عضو', 'Member', 'board', 0, NULL, 1, 4),
  ('أ. شعلان عبدالله الشمراني', 'Mr. Shalan Abdullah Al-Shamrani', 'المدير التنفيذي', 'Executive Director', 'executive', 0, NULL, 1, 0);

INSERT INTO news_categories (slug, name_ar, name_en, sort_order) VALUES
  ('community', 'أنشطة مجتمعية', 'Community activities', 0),
  ('training', 'برامج تدريبية', 'Training', 1),
  ('meetings', 'الاجتماعات', 'Meetings', 2),
  ('student-care', 'رعاية الطلاب', 'Student care', 3);

INSERT INTO posts (slug, title_ar, title_en, excerpt_ar, excerpt_en, body_ar, body_en, category_id, cover_asset_id, published_on, is_featured, is_legacy, is_published, created_by) VALUES
  ('safeer-dates-distribution-2020', 'توزيع ٥٠٠ كرتونة تمور مقدمة من جمعية سفير', 'Distributing 500 boxes of dates donated by Safeer Association', 'ضمن المشاركات المجتمعية للجمعية، وُزّعت الكراتين على المستفيدين بالتعاون مع الجهات الشريكة.', 'As part of the association\'s community work, the boxes were distributed to beneficiaries with partner organisations.', NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'community'), NULL, '2020-07-30', 1, 0, 1, NULL);

INSERT INTO testimonial_themes (title_ar, title_en, description_ar, description_en, is_improvement, sort_order) VALUES
  ('تجربة تعليمية ممتازة', 'An excellent learning experience', 'امتنان للدروس والمحاضرات التي تقدّمها الجمعية، وإشادة بأسلوب التعليم الشامل والميسّر.', 'Gratitude for the association\'s classes and lectures, and praise for its clear, accessible teaching.', 0, 0),
  ('دعم شخصي', 'Personal support', 'دعم فردي في فهم الإسلام أو في تبنّيه كدين جديد.', 'One-to-one support in understanding Islam or in embracing it as a new faith.', 0, 1),
  ('بيئة مرحبة', 'A welcoming environment', 'بيئة دافئة تُشعر المستفيد بالراحة والانتماء.', 'A warm environment where people feel comfortable and that they belong.', 0, 2),
  ('تنظيم الفعاليات', 'Event organisation', 'تقدير للأنشطة مع اقتراحات بتحسين التنظيم والتواصل.', 'Appreciation for the activities, with suggestions to improve organisation and communication.', 1, 3),
  ('موارد إضافية', 'More resources', 'اقتراحات بزيادة الموارد التعليمية من كتب ومقالات.', 'Suggestions to expand educational resources such as books and articles.', 1, 4);

INSERT INTO testimonials (quote_ar, quote_en, author_name, author_desc_ar, author_desc_en, status, is_featured, source, source_message_id, sort_order) VALUES
  ('كنت في زيارة لأحد الأصدقاء وحضرت معهم محاضرة من محاضرات الجمعية — [يُستكمل النص الكامل للشهادة من لوحة التحكم].', 'I was visiting a friend and attended one of the association\'s lectures with them — [full testimonial completed from the dashboard].', 'ع. ج', 'مستفيد من برامج الجمعية', 'Programme beneficiary', 'published', 1, 'manual', NULL, 0);

INSERT INTO doc_categories (slug, name_ar, name_en, is_published, sort_order) VALUES
  ('licences', 'التراخيص', 'Licences', 1, 0),
  ('policies-regulations', 'السياسات واللوائح', 'Policies & regulations', 1, 1),
  ('meeting-minutes', 'محاضر الاجتماعات', 'Meeting minutes', 1, 2),
  ('annual-reports', 'التقارير السنوية', 'Annual reports', 1, 3);

INSERT INTO mail_templates (`key`, name_ar, name_en, subject_ar, subject_en, body_ar, body_en, variables, is_enabled, updated_by) VALUES
  ('contact_ack', 'تأكيد استلام رسالة التواصل', 'Contact acknowledgement', 'شكرًا لتواصلك مع جمعية سفير الدعوية', 'Thank you for contacting Safeer Association', 'مرحبًا {{name}}،\n\nشكرًا لتواصلك مع جمعية سفير الدعوية. وصلتنا رسالتك وسيتواصل معك أحد أعضاء الفريق في أقرب وقت ممكن.\n\nمع تحياتنا،\nفريق جمعية سفير', 'Hello {{name}},\n\nThank you for contacting Safeer Da\'wah Association. We have received your message, and a member of our team will get back to you as soon as possible.\n\nWith appreciation,\nThe Safeer Association Team', '[\"name\"]', 1, NULL),
  ('contact_notify', 'إشعار رسالة تواصل جديدة', 'New contact message notification', 'رسالة تواصل جديدة من {{name}}', 'New contact message from {{name}}', 'وصلت رسالة تواصل جديدة عبر الموقع.\n\n**الاسم:** {{name}}\n**البريد الإلكتروني:** {{email}}\n**الهاتف:** {{phone}}\n**الموضوع:** {{subject}}\n\n**نص الرسالة:**\n{{message}}\n\nيمكنك عرض الرسالة والرد عليها من لوحة التحكم: [{{link}}]({{link}})', 'A new contact message has arrived through the website.\n\n**Name:** {{name}}\n**Email:** {{email}}\n**Phone:** {{phone}}\n**Subject:** {{subject}}\n\n**Message:**\n{{message}}\n\nView and reply to it from the dashboard: [{{link}}]({{link}})', '[\"name\",\"email\",\"phone\",\"subject\",\"message\",\"link\"]', 1, NULL),
  ('user_invite', 'دعوة مستخدم جديد', 'User invitation', 'دعوة للانضمام إلى لوحة تحكم جمعية سفير', 'You\'re invited to the Safeer Association dashboard', 'مرحبًا {{name}}،\n\nدعاك {{inviter}} للانضمام إلى فريق لوحة تحكم جمعية سفير الدعوية بصلاحية {{role}}. لإنشاء كلمة مرورك وتفعيل حسابك، يرجى الضغط على الرابط التالي خلال 48 ساعة:\n\n[{{link}}]({{link}})\n\nإذا لم تكن تتوقع هذه الدعوة، يمكنك تجاهل هذه الرسالة بأمان.', 'Hello {{name}},\n\n{{inviter}} has invited you to join the Safeer Association dashboard team with {{role}} access. To set your password and activate your account, please follow this link within 48 hours:\n\n[{{link}}]({{link}})\n\nIf you weren\'t expecting this invitation, you can safely ignore this message.', '[\"name\",\"inviter\",\"role\",\"link\"]', 1, NULL),
  ('password_reset', 'إعادة تعيين كلمة المرور', 'Password reset', 'إعادة تعيين كلمة المرور', 'Reset your password', 'مرحبًا {{name}}،\n\nتلقينا طلبًا لإعادة تعيين كلمة المرور الخاصة بحسابك في لوحة تحكم جمعية سفير. يرجى الضغط على الرابط التالي خلال 60 دقيقة لتعيين كلمة مرور جديدة:\n\n[{{link}}]({{link}})\n\nإذا لم تطلب ذلك، تجاهل هذه الرسالة ولن يتغير شيء في حسابك.', 'Hello {{name}},\n\nWe received a request to reset the password for your Safeer Association dashboard account. Please follow this link within 60 minutes to set a new password:\n\n[{{link}}]({{link}})\n\nIf you didn\'t request this, you can safely ignore this message and nothing will change.', '[\"name\",\"link\"]', 1, NULL),
  ('application_started', 'بدء طلب منحة', 'Scholarship application started', 'بدأت طلب منحة برقم {{reference}}', 'You started a scholarship application — {{reference}}', 'مرحبًا {{name}}،\n\nبدأت تسجيل طلب منحة في جمعية سفير الدعوية، ورقم طلبك هو **{{reference}}**. يُحفَظ تقدّمك تلقائيًا، ويمكنك العودة لإكمال بقية الخطوات من بوابة الطالب في أي وقت:\n\n[{{link}}]({{link}})\n\nإن لم تُكمل الطلب الآن، يمكنك العودة إليه لاحقًا باستخدام رقم الطلب أو بريدك الإلكتروني.', 'Hello {{name}},\n\nYou started a scholarship application with Safeer Association. Your application reference is **{{reference}}**. Your progress is saved automatically, and you can return to finish the remaining steps from the student portal at any time:\n\n[{{link}}]({{link}})\n\nIf you don\'t finish now, you can come back later using your reference or email.', '[\"name\",\"reference\",\"link\"]', 1, NULL),
  ('application_submitted', 'إرسال طلب المنحة', 'Scholarship application submitted', 'استلمنا طلبك رقم {{reference}}', 'We received your application — {{reference}}', 'مرحبًا {{name}}،\n\nاستلمنا طلب المنحة الخاص بك برقم **{{reference}}**، وسيبدأ فريق الجمعية بمراجعة بياناتك ومستنداتك قريبًا. يمكنك متابعة حالة الطلب في أي وقت من بوابة الطالب:\n\n[{{link}}]({{link}})\n\nسنُعلمك بالبريد الإلكتروني والرسائل النصية عند أي تحديث.', 'Hello {{name}},\n\nWe have received your scholarship application, reference **{{reference}}**. Our team will begin reviewing your details and documents shortly. You can follow its status at any time from the student portal:\n\n[{{link}}]({{link}})\n\nWe will notify you by email and SMS with any update.', '[\"name\",\"reference\",\"link\"]', 1, NULL),
  ('application_status_changed', 'تحديث حالة الطلب', 'Application status update', 'تحديث على طلبك {{reference}}: {{status}}', 'Update on your application {{reference}}: {{status}}', 'مرحبًا {{name}}،\n\nتحدّثت حالة طلبك رقم **{{reference}}** إلى: **{{status}}**.\n\n{{note}}\n\nيمكنك مراجعة التفاصيل كاملة من بوابة الطالب:\n\n[{{link}}]({{link}})', 'Hello {{name}},\n\nThe status of your application **{{reference}}** has changed to: **{{status}}**.\n\n{{note}}\n\nYou can review the full details from the student portal:\n\n[{{link}}]({{link}})', '[\"name\",\"reference\",\"status\",\"note\",\"link\"]', 1, NULL),
  ('document_rejected', 'رفض مستند مرفوع', 'Uploaded document rejected', 'مطلوب إجراء: مستند في طلبك {{reference}} يحتاج إعادة رفع', 'Action needed: a document in {{reference}} needs re-upload', 'مرحبًا {{name}}،\n\nراجع فريق الجمعية مستند **{{docType}}** ضمن طلبك رقم **{{reference}}**، ولم يُقبل للسبب التالي:\n\n> {{reason}}\n\nيرجى إعادة رفع نسخة أوضح من بوابة الطالب لاستكمال المراجعة:\n\n[{{link}}]({{link}})', 'Hello {{name}},\n\nOur team reviewed the **{{docType}}** document in your application **{{reference}}**, and it was not accepted for the following reason:\n\n> {{reason}}\n\nPlease re-upload a clearer copy from the student portal so the review can continue:\n\n[{{link}}]({{link}})', '[\"name\",\"reference\",\"docType\",\"reason\",\"link\"]', 1, NULL),
  ('documents_requested', 'طلب استكمال مستندات', 'Documents requested', 'مطلوب استكمال مستندات لطلبك {{reference}}', 'Documents needed for your application {{reference}}', 'مرحبًا {{name}}،\n\nلاستكمال مراجعة طلبك رقم **{{reference}}**، نحتاج منك رفع أو استبدال المستندات التالية:\n\n{{docTypes}}\n\n{{message}}\n\nيمكنك رفعها من بوابة الطالب:\n\n[{{link}}]({{link}})', 'Hello {{name}},\n\nTo continue reviewing your application **{{reference}}**, please upload or replace the following documents:\n\n{{docTypes}}\n\n{{message}}\n\nYou can upload them from the student portal:\n\n[{{link}}]({{link}})', '[\"name\",\"reference\",\"docTypes\",\"message\",\"link\"]', 1, NULL),
  ('message_reply', 'رد على رسالة تواصل', 'Reply to your message', 'رد جمعية سفير على رسالتك', 'Safeer Association replied to your message', 'مرحبًا {{name}}،\n\n{{message}}\n\n—\nفريق جمعية سفير الدعوية', 'Hello {{name}},\n\n{{message}}\n\n—\nThe Safeer Da\'wah Association Team', '[\"name\",\"message\"]', 1, NULL),
  ('otp_code', 'رمز التحقق لمرة واحدة', 'One-time verification code', 'رمز الدخول إلى بوابة الطالب: {{code}}', 'Your student portal sign-in code: {{code}}', 'رمز الدخول إلى بوابة الطالب هو: **{{code}}**\n\nصالح لمدة {{minutes}} دقائق. لا تشارك هذا الرمز مع أحد.\n\nإذا لم تطلب هذا الرمز، تجاهل هذه الرسالة.', 'Your student portal sign-in code is: **{{code}}**\n\nIt is valid for {{minutes}} minutes. Do not share this code with anyone.\n\nIf you did not request it, you can ignore this message.', '[\"code\",\"minutes\"]', 1, NULL);

INSERT INTO sms_templates (`key`, name_ar, name_en, body_ar, body_en, variables, is_enabled, updated_by) VALUES
  ('otp_code', 'رمز التحقق', 'Verification code', 'رمز الدخول إلى بوابة سفير: {{code}} (صالح {{minutes}} دقائق)', 'Your Safeer portal code: {{code}} (valid {{minutes}} min)', '[\"code\",\"minutes\"]', 1, NULL),
  ('application_submitted', 'إرسال الطلب', 'Application submitted', 'جمعية سفير: استلمنا طلبك {{reference}}. تابع حالته عبر بوابة الطالب.', 'Safeer: we received your application {{reference}}. Track it in the student portal.', '[\"reference\"]', 1, NULL),
  ('application_status_changed', 'تحديث الحالة', 'Status update', 'جمعية سفير: تحدّثت حالة طلبك {{reference}} إلى {{status}}.', 'Safeer: your application {{reference}} status changed to {{status}}.', '[\"reference\",\"status\"]', 1, NULL),
  ('documents_requested', 'طلب مستندات', 'Documents requested', 'جمعية سفير: يلزم استكمال مستندات لطلبك {{reference}}. راجع بوابة الطالب.', 'Safeer: documents are needed for application {{reference}}. Check the student portal.', '[\"reference\"]', 1, NULL);

INSERT INTO mail_settings (id, is_enabled, driver, host, port, encryption, username, password_encrypted, from_name_ar, from_name_en, from_email, reply_to, notify_email, last_test_at, last_test_ok, last_test_error, updated_by) VALUES
  (1, 0, 'log', NULL, NULL, 'starttls', NULL, NULL, 'جمعية سفير الدعوية', 'Safeer Da\'wah Association', 'info@safeer-sa.org', 'info@safeer-sa.org', 'info@safeer-sa.org', NULL, NULL, NULL, NULL);

INSERT INTO sms_settings (id, is_enabled, driver, provider_url, token_encrypted, sender_name, last_test_at, last_test_ok, last_test_error, updated_by) VALUES
  (1, 0, 'log', NULL, NULL, 'Safeer', NULL, NULL, NULL, NULL);

