-- 014_about_scholarships_sections.sql
-- safeer-backend-fix-prompt.md B18: the `about` and `scholarships` pages had
-- no sections. These are the prototype's own blocks (pAbout(), pScholar():
-- each secHead's label, heading and lead, and its buttons), generated by
-- tools/seed-from-prototype.mjs (buildInnerPageSections) — no invented
-- content. The cards and lists inside the blocks are about_items, served by
-- the public GET about-items:
--   about/vision_mission   ← kind vision, mission
--   about/goals            ← kind goal
--   scholarships/pillars   ← kind care_pillar
--   scholarships/steps     ← kind scholarship_step
--   scholarships/requirements ← kind requirement
-- INSERT IGNORE: uq_page_section_key (page_id, section_key) keeps a section
-- an editor already created with the same key.

INSERT IGNORE INTO page_sections (page_id, section_key, label_ar, label_en, heading_ar, heading_en, body_ar, body_en, primary_button_label_ar, primary_button_label_en, primary_button_url, secondary_button_label_ar, secondary_button_label_en, secondary_button_url, image_asset_id, is_published, sort_order) VALUES
  ((SELECT id FROM pages WHERE slug = 'about'), 'intro', 'عن الجمعية', 'About the association', 'نشر تعاليم الإسلام السمحة ورعاية طلابه', 'Sharing Islam\'s teachings and caring for its students', 'جمعية سفير الدعوية جمعية تهدف إلى نشر الإسلام وتعاليمه السمحة بين الناس من خلال العديد من الخدمات والأنشطة. تقدم الجمعية برامج توعوية وتعليمية تستهدف مختلف الفئات العمرية، وتعقد دورات تدريبية لتعزيز فهم الإسلام وتعاليمه.\n\nكما تنظّم الجمعية محاضرات وندوات دينية، وتهتم بتوزيع الكتب والنشرات التثقيفية التي تشرح المبادئ الإسلامية بشكل مبسّط وواضح.', 'Safeer Association works to share Islam and its teachings through a range of services and activities. It runs awareness and education programmes for all age groups and holds training courses that deepen understanding of Islam.\n\nIt also organises lectures and seminars, and distributes books and educational material explaining Islamic principles clearly and simply.', 'التراخيص والسياسات', 'Licences & policies', '/documents', 'مجلس الإدارة', 'Board of directors', '/board', NULL, 1, 0),
  ((SELECT id FROM pages WHERE slug = 'about'), 'vision_mission', 'مهمتنا', 'Our mission', 'الرؤية والرسالة والأهداف', 'Vision, mission and goals', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1),
  ((SELECT id FROM pages WHERE slug = 'about'), 'goals', 'الأهداف', 'Goals', NULL, NULL, 'خمسة أهداف معلنة تحكم كل برامج الجمعية وتُقاس عليها.', 'Five stated goals that govern and measure every programme.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 2),
  ((SELECT id FROM pages WHERE slug = 'about'), 'governance', 'الحوكمة', 'Governance', 'الاجتماعات والمحاضر', 'Meetings and minutes', 'تُنشر محاضر الاجتماعات كملفات PDF قابلة للتحميل، وتُدار من قسم «المستندات» في لوحة التحكم.', 'Minutes are published as downloadable PDFs, managed from the Documents section of the dashboard.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3),
  ((SELECT id FROM pages WHERE slug = 'scholarships'), 'hero', 'منح الوافدين', 'Scholarships', 'منح الوافدين للدراسة بالجامعات السعودية', 'Scholarships for international students in Saudi universities', 'تلعب الجمعية دوراً محورياً في رعاية طلاب المنح الدوليين، عبر دعم شامل يسهّل تكيّفهم ويعزّز تجربتهم الأكاديمية والثقافية.', 'The association plays a central role in caring for international scholarship students, with support that eases adaptation and enriches their academic and cultural experience.', 'ابدأ الطلب الآن', 'Start your application', '/apply', 'تتبّع طلبي', 'Track my application', '/portal/login', NULL, 1, 0),
  ((SELECT id FROM pages WHERE slug = 'scholarships'), 'pillars', 'أوجه الرعاية', 'How we help', 'أربعة أوجه للدعم', 'Four kinds of support', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1),
  ((SELECT id FROM pages WHERE slug = 'scholarships'), 'steps', 'الخطوات', 'Steps', 'من الطلب إلى القبول', 'From application to acceptance', 'كل خطوة لها حالة ظاهرة للطالب في بوابته، وحالة مقابلة في لوحة تحكم الجمعية.', 'Each step has a status visible in the student portal and a matching one in the dashboard.', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 2),
  ((SELECT id FROM pages WHERE slug = 'scholarships'), 'requirements', 'المتطلبات', 'Requirements', 'ما تحتاجه قبل التقديم', 'What to prepare', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 3),
  ((SELECT id FROM pages WHERE slug = 'scholarships'), 'cta', 'دعوة للتسجيل', 'Call to action', 'جاهز للتقديم؟', 'Ready to apply?', 'النموذج يحفظ تقدّمك تلقائياً، ويمكنك العودة لإكماله لاحقاً من بوابة الطالب.', 'The form saves your progress automatically — come back and finish it from the student portal.', 'تسجيل طلب منحة', 'Apply for a scholarship', '/apply', 'لديك سؤال؟ تواصل معنا', 'Questions? Contact us', '/contact', NULL, 1, 4);
