-- generated by tools/seed-from-prototype.mjs. Do not hand-edit.
-- Sample content for dev and staging only — never applied in production (scripts/migrate.mjs excludes migrations/dev/).

-- media_assets: 12 rows — 1 real logo + 7 placeholder images + 4 placeholder PDFs

INSERT INTO media_assets (public_id, kind, mime_type, size_bytes, original_name, storage_key, checksum_sha256, width_px, height_px, alt_ar, alt_en, uploaded_by) VALUES
  ('0793959b-a19c-4c7c-aa0c-e2e1d79e534d', 'image', 'image/png', 10066, 'safeer-logo.png', 'assets/2026/09/0793959b-a19c-4c7c-aa0c-e2e1d79e534d.png', 'b9d5d6fe86bdabab45cb395d3e98b69e59187dba31c447b20d8cb507a7dab1a6', 150, 228, 'جمعية سفير الدعوية', 'Safeer Association', NULL),
  ('3cd3625c-5a49-4d4e-aed2-e78009e1a774', 'image', 'image/jpeg', 21275, 'hero.jpg', 'assets/2026/09/3cd3625c-5a49-4d4e-aed2-e78009e1a774.jpg', '9ac232e9b97f5204d6eacbcab8eed128088ba79fbef375f054feaa36b64b3bf6', 1600, 1200, 'صورة الواجهة: طلاب المنح في فعالية الجمعية', 'Hero image: scholarship students at an association event', NULL),
  ('1383fafb-e3fe-4142-a542-ad8ca4311931', 'image', 'image/jpeg', 17494, 'news-cover-1.jpg', 'assets/2026/09/1383fafb-e3fe-4142-a542-ad8ca4311931.jpg', '745c318fd9606431fe9a9f284588ed9e979978cf72b228dd8e7847bda5dd0cbc', 1600, 1200, 'صورة خبر توزيع كراتين التمور', 'Article image: dates distribution', NULL),
  ('ec1f7b89-4665-42d1-93dd-ffd5cfc3dc8e', 'image', 'image/jpeg', 16597, 'news-cover-2.jpg', 'assets/2026/09/ec1f7b89-4665-42d1-93dd-ffd5cfc3dc8e.jpg', '234a8bf31068ebc9d684d74f0d826cbcebcb897f030b342c2e96c8bcafed4e60', 1600, 1200, 'صورة خبر دورة اللغة العربية', 'Article image: Arabic course', NULL),
  ('247ae010-5f62-4d35-bc98-3cdaae7e9bc8', 'image', 'image/jpeg', 17678, 'news-cover-3.jpg', 'assets/2026/09/247ae010-5f62-4d35-bc98-3cdaae7e9bc8.jpg', '19fdb23d02724510568e8c14564485427bddf198c4f77c562ba77672478f7dc1', 1600, 1200, 'صورة خبر اللقاء التوجيهي', 'Article image: orientation session', NULL),
  ('233a4592-140e-4a17-bd9e-e924b8eb6974', 'image', 'image/jpeg', 15014, 'partner-logo-1.jpg', 'assets/2026/09/233a4592-140e-4a17-bd9e-e924b8eb6974.jpg', '1f8b994a7b43b8a32474c7d7279ac9278d69e1be2aa1412d45aa77ba62cf7d19', 1600, 1200, 'شعار شريك', 'Partner logo', NULL),
  ('75f92cfe-b43d-48b0-aa4a-8754382504e6', 'image', 'image/jpeg', 14700, 'partner-logo-2.jpg', 'assets/2026/09/75f92cfe-b43d-48b0-aa4a-8754382504e6.jpg', '7ba708bd1b6ef7292fc2ed1bc8c05d1639800cc525017878d3d184700fa75a6a', 1600, 1200, 'شعار شريك', 'Partner logo', NULL),
  ('95b52b01-7a1d-4f05-96e9-6624bf29b9b9', 'image', 'image/jpeg', 15515, 'partner-logo-3.jpg', 'assets/2026/09/95b52b01-7a1d-4f05-96e9-6624bf29b9b9.jpg', '0a369506b05520796499e845dcb561257189f97cbb1ac5b9c41ad34537bf4b00', 1600, 1200, 'شعار شريك', 'Partner logo', NULL),
  ('6251f38c-de6b-4a0f-b92c-f6964fd0b3bd', 'pdf', 'application/pdf', 593, 'licence.pdf', 'assets/2026/09/6251f38c-de6b-4a0f-b92c-f6964fd0b3bd.pdf', 'bd3b71e63021250a5ffd865f921aaaa607387e6dd2430e8ba19f8dff43067acd', NULL, NULL, NULL, NULL, NULL),
  ('1dc2d4ba-82a2-4a74-bbc3-42ee75a58510', 'pdf', 'application/pdf', 592, 'bylaws.pdf', 'assets/2026/09/1dc2d4ba-82a2-4a74-bbc3-42ee75a58510.pdf', '36b24694e72d857e7e00174fa929db06d59a33a5bc9e5d7b028acf8e03c6dc8e', NULL, NULL, NULL, NULL, NULL),
  ('dafcbca1-f90a-4db9-b677-106a4975f2d3', 'pdf', 'application/pdf', 601, 'minutes-1.pdf', 'assets/2026/09/dafcbca1-f90a-4db9-b677-106a4975f2d3.pdf', 'c16fb2f918692a67c7feb82005c2143811736aed52e0beb77408c6ff0c1638e5', NULL, NULL, NULL, NULL, NULL),
  ('f062c547-81cc-402c-bc3a-1392185ac084', 'pdf', 'application/pdf', 601, 'annual-report-2024.pdf', 'assets/2026/09/f062c547-81cc-402c-bc3a-1392185ac084.pdf', 'fd617b108f7062cc31e156563687b644e03dd83d069fe323364299b67211db58', NULL, NULL, NULL, NULL, NULL);

INSERT INTO media_variants (asset_id, label, storage_key, width_px, size_bytes) VALUES
  ((SELECT id FROM media_assets WHERE checksum_sha256 = 'b9d5d6fe86bdabab45cb395d3e98b69e59187dba31c447b20d8cb507a7dab1a6'), 'thumb', 'assets/2026/09/0793959b-a19c-4c7c-aa0c-e2e1d79e534d-thumb.webp', 150, 6708),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = 'b9d5d6fe86bdabab45cb395d3e98b69e59187dba31c447b20d8cb507a7dab1a6'), 'card', 'assets/2026/09/0793959b-a19c-4c7c-aa0c-e2e1d79e534d-card.webp', 150, 6708),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = 'b9d5d6fe86bdabab45cb395d3e98b69e59187dba31c447b20d8cb507a7dab1a6'), 'full', 'assets/2026/09/0793959b-a19c-4c7c-aa0c-e2e1d79e534d-full.webp', 150, 6708),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '9ac232e9b97f5204d6eacbcab8eed128088ba79fbef375f054feaa36b64b3bf6'), 'thumb', 'assets/2026/09/3cd3625c-5a49-4d4e-aed2-e78009e1a774-thumb.webp', 400, 1356),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '9ac232e9b97f5204d6eacbcab8eed128088ba79fbef375f054feaa36b64b3bf6'), 'card', 'assets/2026/09/3cd3625c-5a49-4d4e-aed2-e78009e1a774-card.webp', 800, 3546),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '9ac232e9b97f5204d6eacbcab8eed128088ba79fbef375f054feaa36b64b3bf6'), 'full', 'assets/2026/09/3cd3625c-5a49-4d4e-aed2-e78009e1a774-full.webp', 1600, 9210),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '745c318fd9606431fe9a9f284588ed9e979978cf72b228dd8e7847bda5dd0cbc'), 'thumb', 'assets/2026/09/1383fafb-e3fe-4142-a542-ad8ca4311931-thumb.webp', 400, 894),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '745c318fd9606431fe9a9f284588ed9e979978cf72b228dd8e7847bda5dd0cbc'), 'card', 'assets/2026/09/1383fafb-e3fe-4142-a542-ad8ca4311931-card.webp', 800, 2600),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '745c318fd9606431fe9a9f284588ed9e979978cf72b228dd8e7847bda5dd0cbc'), 'full', 'assets/2026/09/1383fafb-e3fe-4142-a542-ad8ca4311931-full.webp', 1600, 6848),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '234a8bf31068ebc9d684d74f0d826cbcebcb897f030b342c2e96c8bcafed4e60'), 'thumb', 'assets/2026/09/ec1f7b89-4665-42d1-93dd-ffd5cfc3dc8e-thumb.webp', 400, 830),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '234a8bf31068ebc9d684d74f0d826cbcebcb897f030b342c2e96c8bcafed4e60'), 'card', 'assets/2026/09/ec1f7b89-4665-42d1-93dd-ffd5cfc3dc8e-card.webp', 800, 2240),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '234a8bf31068ebc9d684d74f0d826cbcebcb897f030b342c2e96c8bcafed4e60'), 'full', 'assets/2026/09/ec1f7b89-4665-42d1-93dd-ffd5cfc3dc8e-full.webp', 1600, 6394),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '19fdb23d02724510568e8c14564485427bddf198c4f77c562ba77672478f7dc1'), 'thumb', 'assets/2026/09/247ae010-5f62-4d35-bc98-3cdaae7e9bc8-thumb.webp', 400, 914),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '19fdb23d02724510568e8c14564485427bddf198c4f77c562ba77672478f7dc1'), 'card', 'assets/2026/09/247ae010-5f62-4d35-bc98-3cdaae7e9bc8-card.webp', 800, 2526),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '19fdb23d02724510568e8c14564485427bddf198c4f77c562ba77672478f7dc1'), 'full', 'assets/2026/09/247ae010-5f62-4d35-bc98-3cdaae7e9bc8-full.webp', 1600, 6886),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '1f8b994a7b43b8a32474c7d7279ac9278d69e1be2aa1412d45aa77ba62cf7d19'), 'thumb', 'assets/2026/09/233a4592-140e-4a17-bd9e-e924b8eb6974-thumb.webp', 400, 656),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '1f8b994a7b43b8a32474c7d7279ac9278d69e1be2aa1412d45aa77ba62cf7d19'), 'card', 'assets/2026/09/233a4592-140e-4a17-bd9e-e924b8eb6974-card.webp', 800, 1880),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '1f8b994a7b43b8a32474c7d7279ac9278d69e1be2aa1412d45aa77ba62cf7d19'), 'full', 'assets/2026/09/233a4592-140e-4a17-bd9e-e924b8eb6974-full.webp', 1600, 5464),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '7ba708bd1b6ef7292fc2ed1bc8c05d1639800cc525017878d3d184700fa75a6a'), 'thumb', 'assets/2026/09/75f92cfe-b43d-48b0-aa4a-8754382504e6-thumb.webp', 400, 614),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '7ba708bd1b6ef7292fc2ed1bc8c05d1639800cc525017878d3d184700fa75a6a'), 'card', 'assets/2026/09/75f92cfe-b43d-48b0-aa4a-8754382504e6-card.webp', 800, 1760),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '7ba708bd1b6ef7292fc2ed1bc8c05d1639800cc525017878d3d184700fa75a6a'), 'full', 'assets/2026/09/75f92cfe-b43d-48b0-aa4a-8754382504e6-full.webp', 1600, 5236),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '0a369506b05520796499e845dcb561257189f97cbb1ac5b9c41ad34537bf4b00'), 'thumb', 'assets/2026/09/95b52b01-7a1d-4f05-96e9-6624bf29b9b9-thumb.webp', 400, 726),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '0a369506b05520796499e845dcb561257189f97cbb1ac5b9c41ad34537bf4b00'), 'card', 'assets/2026/09/95b52b01-7a1d-4f05-96e9-6624bf29b9b9-card.webp', 800, 2044),
  ((SELECT id FROM media_assets WHERE checksum_sha256 = '0a369506b05520796499e845dcb561257189f97cbb1ac5b9c41ad34537bf4b00'), 'full', 'assets/2026/09/95b52b01-7a1d-4f05-96e9-6624bf29b9b9-full.webp', 1600, 5886);

-- the home page's hero section picks up the placeholder hero image

UPDATE page_sections SET image_asset_id = (SELECT id FROM media_assets WHERE checksum_sha256 = '9ac232e9b97f5204d6eacbcab8eed128088ba79fbef375f054feaa36b64b3bf6')
WHERE page_id = (SELECT id FROM pages WHERE slug = 'home') AND section_key = 'hero';

-- one extra news category for the legacy medical-template posts, not part of 002's 4 real categories

INSERT INTO news_categories (slug, name_ar, name_en, sort_order) VALUES
  ('legacy-template', 'محتوى قالب سابق', 'Legacy template content', 99);

INSERT INTO partners (name_ar, name_en, category, url, logo_asset_id, is_published, sort_order) VALUES
  ('وزارة الموارد البشرية والتنمية الاجتماعية', 'Ministry of Human Resources and Social Development', 'government', NULL, (SELECT id FROM media_assets WHERE checksum_sha256 = '1f8b994a7b43b8a32474c7d7279ac9278d69e1be2aa1412d45aa77ba62cf7d19'), 1, 0),
  ('الهيئة العامة للمنح الدراسية', 'General Authority for Scholarships', 'government', NULL, NULL, 1, 1),
  ('جامعة الملك سعود', 'King Saud University', 'university', NULL, (SELECT id FROM media_assets WHERE checksum_sha256 = '7ba708bd1b6ef7292fc2ed1bc8c05d1639800cc525017878d3d184700fa75a6a'), 1, 2),
  ('جامعة الإمام محمد بن سعود الإسلامية', 'Imam Muhammad ibn Saud Islamic University', 'university', NULL, NULL, 1, 3),
  ('جمعية البر بالرياض', 'Al Birr Society in Riyadh', 'association', NULL, NULL, 1, 4),
  ('مؤسسة العطاء الخيرية', 'Al-Ataa Charitable Foundation', 'supporter', NULL, (SELECT id FROM media_assets WHERE checksum_sha256 = '0a369506b05520796499e845dcb561257189f97cbb1ac5b9c41ad34537bf4b00'), 1, 5),
  ('شركة سدير القابضة', 'Sudair Holding Company', 'supporter', NULL, NULL, 1, 6);

INSERT INTO documents (category_id, title_ar, title_en, asset_id, doc_date, download_count, is_published, sort_order) VALUES
  ((SELECT id FROM doc_categories WHERE slug = 'licences'), 'ترخيص الجمعية', 'Association licence', (SELECT id FROM media_assets WHERE checksum_sha256 = 'bd3b71e63021250a5ffd865f921aaaa607387e6dd2430e8ba19f8dff43067acd'), '2019-03-10', 0, 1, 0),
  ((SELECT id FROM doc_categories WHERE slug = 'policies-regulations'), 'اللائحة الأساسية للجمعية', 'Association bylaws', (SELECT id FROM media_assets WHERE checksum_sha256 = '36b24694e72d857e7e00174fa929db06d59a33a5bc9e5d7b028acf8e03c6dc8e'), '2019-05-01', 0, 1, 1),
  ((SELECT id FROM doc_categories WHERE slug = 'meeting-minutes'), 'محضر اجتماع مجلس الإدارة رقم ١', 'Board meeting minutes no. 1', (SELECT id FROM media_assets WHERE checksum_sha256 = 'c16fb2f918692a67c7feb82005c2143811736aed52e0beb77408c6ff0c1638e5'), '2024-01-15', 0, 1, 2),
  ((SELECT id FROM doc_categories WHERE slug = 'annual-reports'), 'تقرير الأنشطة السنوي 2024', 'Annual activity report 2024', (SELECT id FROM media_assets WHERE checksum_sha256 = 'fd617b108f7062cc31e156563687b644e03dd83d069fe323364299b67211db58'), '2024-05-01', 0, 1, 3);

INSERT INTO posts (slug, title_ar, title_en, excerpt_ar, excerpt_en, body_ar, body_en, category_id, cover_asset_id, published_on, is_featured, is_legacy, is_published, created_by) VALUES
  ('legacy-neurology-template', 'محتوى قالب إنجليزي قديم من موقع طبي — يُحذف', 'Everyone is worried when the test results come back positive', NULL, NULL, NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'legacy-template'), NULL, '2020-07-30', 0, 1, 0, NULL),
  ('legacy-laboratory-template', 'محتوى قالب إنجليزي قديم من موقع طبي — يُحذف', '6 Tips to Protect Your Mental Health When You Are Sick', NULL, NULL, NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'legacy-template'), NULL, '2020-07-30', 0, 1, 0, NULL),
  ('legacy-pathology-template', 'محتوى قالب إنجليزي قديم من موقع طبي — يُحذف', 'Tips for Eating Healthy When You Are Working From Home', NULL, NULL, NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'legacy-template'), NULL, '2020-07-30', 0, 1, 0, NULL),
  ('arabic-course-for-non-native-speakers-2024', 'الجمعية تنظّم دورة تدريبية في تعليم اللغة العربية لغير الناطقين بها', 'Association runs a training course teaching Arabic to non-native speakers', 'شارك عدد من طلاب المنح في دورة مكثفة لتعليم اللغة العربية استعداداً للفصل الدراسي الجديد.', 'A group of scholarship students took part in an intensive Arabic course ahead of the new term.', NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'training'), (SELECT id FROM media_assets WHERE checksum_sha256 = '234a8bf31068ebc9d684d74f0d826cbcebcb897f030b342c2e96c8bcafed4e60'), '2024-02-10', 0, 0, 1, NULL),
  ('new-student-orientation-2024', 'لقاء توجيهي جديد لطلاب المنح الوافدين', 'New orientation session for incoming scholarship students', 'استقبلت الجمعية دفعة جديدة من طلاب المنح الوافدين في لقاء تعريفي بالخدمات والبرامج المتاحة.', 'The association welcomed a new group of incoming scholarship students in an orientation session on its services and programmes.', NULL, NULL, (SELECT id FROM news_categories WHERE slug = 'student-care'), (SELECT id FROM media_assets WHERE checksum_sha256 = '19fdb23d02724510568e8c14564485427bddf198c4f77c562ba77672478f7dc1'), '2024-09-01', 0, 0, 1, NULL);

-- NEWS1 (the 002-seeded featured post) picks up a placeholder cover here, since 002 seeds no media

UPDATE posts SET cover_asset_id = (SELECT id FROM media_assets WHERE checksum_sha256 = '745c318fd9606431fe9a9f284588ed9e979978cf72b228dd8e7847bda5dd0cbc')
WHERE slug = 'safeer-dates-distribution-2020';

INSERT INTO contact_messages (name, phone, email, subject, body, status, locale, ip_hash, user_agent) VALUES
  ('مها العتيبي', '+966 55 123 4567', 'maha.alotaibi@example.com', 'scholarship', 'السلام عليكم، أرغب في معرفة شروط التقديم على المنحة وموعد فتح باب التسجيل القادم.', 'unread', 'ar', NULL, NULL),
  ('مؤسسة العطاء الخيرية', '+966 11 456 7890', 'info@al-ataa-example.org', 'partnership', 'نحن جهة خيرية مهتمة بدعم برامج رعاية طلاب المنح، ونود معرفة آليات الشراكة مع الجمعية.', 'read', 'ar', NULL, NULL),
  ('سالم الحربي', NULL, 'salem.harbi@example.com', 'feedback', 'أقترح زيادة الموارد التعليمية المنشورة على الموقع، خصوصاً في مجال تعليم اللغة العربية.', 'archived', 'ar', NULL, NULL),
  ('فاطمة الزهراني', '+966 50 987 6543', 'fatima.zahrani@example.com', 'scholarship', 'هل يمكن التقديم على المنحة لمرحلة الدكتوراه، وما المستندات الإضافية المطلوبة لهذه المرحلة؟', 'read', 'ar', NULL, NULL),
  ('خالد النعيمي', NULL, 'khalid.alnuaimi@example.com', 'other', 'شكراً لكم على الجهود المبذولة في خدمة طلاب المنح، جزاكم الله خيراً.', 'unread', 'ar', NULL, NULL);

-- applications SA-2026-00179..00184 — see APPLICATIONS in this script for the ascending-reference-order / predicted-id note

INSERT INTO applications (reference, status, current_step, first_name, middle_name, last_name, birth_date, phone, nationality, id_number, email, current_job, gender, university, major, degree_level, scholarship_note, consent_at, submitted_at, decided_at, assigned_reviewer_id, locale) VALUES
  ('SA-2026-00179', 'under_review', 3, 'نور', 'جهان', 'خان', '1999-04-12', '+91 98765 43210', 'IN', '2456781290', 'noorjahan.khan@example.com', NULL, 'female', 'الجامعة الإسلامية بالمدينة المنورة', 'الدعوة وأصول الدين', 'master', 'مبتعثة لدراسة الدعوة وأصول الدين ورغبة في العمل التعليمي بعد التخرج.', '2026-02-10 09:15:00.000', '2026-02-10 09:15:00.000', NULL, NULL, 'ar'),
  ('SA-2026-00180', 'rejected', 3, 'عبد', 'الرحمن', 'الحضرمي', '2000-11-02', '+967 71 234 5678', 'YE', '2078451236', 'abdulrahman.hadrami@example.com', NULL, 'male', 'جامعة الملك عبدالعزيز', 'اللغة العربية', 'bachelor', NULL, '2026-01-15 11:40:00.000', '2026-01-15 11:40:00.000', '2026-02-01 13:00:00.000', NULL, 'ar'),
  ('SA-2026-00181', 'new', 3, 'ياسمين', 'عبد الرحمن', 'طه', '1997-06-20', '+20 100 123 4567', 'EG', '2988012345', 'yasmin.taha@example.com', 'معيدة بكلية الشريعة', 'female', 'جامعة الإمام محمد بن سعود الإسلامية', 'الفقه المقارن', 'phd', 'باحثة ماجستير سابقاً وتطمح لإكمال الدكتوراه في الفقه المقارن.', '2026-09-20 16:05:00.000', '2026-09-20 16:05:00.000', NULL, NULL, 'ar'),
  ('SA-2026-00182', 'accepted', 3, 'محمد', 'لديب', 'خان', '2001-01-30', '+92 300 1234567', 'PK', '2167834529', 'muhammad.ludeeb@example.com', NULL, 'male', 'جامعة الملك سعود', 'علوم الحاسب', 'bachelor', NULL, '2026-03-05 08:30:00.000', '2026-03-05 08:30:00.000', '2026-04-10 10:00:00.000', NULL, 'ar'),
  ('SA-2026-00183', 'docs_missing', 3, 'نور', 'الهدى', 'إسماعيل', '1998-09-08', '+62 812 3456 7890', 'ID', '2345098761', 'nurulhuda.ismail@example.com', NULL, 'female', 'جامعة أم القرى', 'أصول الدين', 'master', NULL, '2026-05-12 14:20:00.000', '2026-05-12 14:20:00.000', NULL, NULL, 'ar'),
  ('SA-2026-00184', 'under_review', 3, 'إبراهيم', 'موسى', 'بالو', '2002-03-17', '+234 803 123 4567', 'NG', '2456123980', 'ibrahim.musa@example.com', NULL, 'male', 'الجامعة الإسلامية بالمدينة المنورة', 'الشريعة الإسلامية', 'bachelor', 'قدِم حديثاً إلى المملكة والتحق بالمنحة عقب اجتياز الاختبار التأهيلي.', '2026-08-01 10:00:00.000', '2026-08-01 10:00:00.000', NULL, NULL, 'ar');

INSERT INTO application_documents (application_id, doc_type, original_name, storage_key, mime, size_bytes, checksum, status, rejection_reason, reviewed_by, reviewed_at, superseded_at) VALUES
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'id_copy', 'id_copy.jpg', 'private/applications/1/40647918-444e-44a2-adea-eaa9ff6e5778.jpg', 'image/jpeg', 17475, '2281c35e2fa29439e0600915dc36802190aa8213e4b061a53b9bfe01589c6736', 'accepted', NULL, NULL, '2026-02-10 09:15:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'certificate', 'certificate.pdf', 'private/applications/1/93b9f2f0-f472-422f-ace3-fed8b6ba4c21.pdf', 'application/pdf', 610, '1ee35b56c0c1019f10e6b4224a92e65caa13945e87882667b171917a90589cc1', 'accepted', NULL, NULL, '2026-02-10 09:15:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'admission_letter', 'admission_letter.pdf', 'private/applications/1/fd8e17dd-596d-4138-88d7-f3319d950070.pdf', 'application/pdf', 617, '1de5c3011c06845b8f3ad3126297f5be275150041a8755430f555d01bb5600f3', 'under_review', NULL, NULL, NULL, NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'id_copy', 'id_copy.jpg', 'private/applications/4/9af82b65-ffea-4548-8bd8-3d98f1188d13.jpg', 'image/jpeg', 18297, '5407a2679e5d2bf5d44f67dde09a769dfecb31c5758931eb456b04c3f1ce5ffe', 'accepted', NULL, NULL, '2026-03-05 08:30:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'certificate', 'certificate.pdf', 'private/applications/4/75400a51-50be-4ffb-9d1f-5c6bb4dd9e15.pdf', 'application/pdf', 610, '73fa68d88e1d12eee081368e6657842287fd61ef21f0a27646623d25432dbda5', 'accepted', NULL, NULL, '2026-03-05 08:30:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'admission_letter', 'admission_letter.pdf', 'private/applications/4/09ad7769-a299-4f66-ba73-53d60f43d4fc.pdf', 'application/pdf', 617, '7fac11240d2d5c7134f0b45ff2430b331bb7db10450553fdc8e5789d4755a83b', 'accepted', NULL, NULL, '2026-03-05 08:30:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'id_copy', 'id_copy.jpg', 'private/applications/5/0808165c-3842-48fd-9080-8c39d8e6a6cb.jpg', 'image/jpeg', 17431, 'f6c54707934ab13bfcab671958f6ef83bae45a4351fb0e9c5954a858e9ff4514', 'rejected', 'صورة الهوية غير واضحة', NULL, '2026-05-12 14:20:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'certificate', 'certificate.pdf', 'private/applications/5/f93c30d5-073f-4be7-8e88-498446d6eaee.pdf', 'application/pdf', 610, '77ecf13f7b420cdbb20febe7a2ed8e4adf34387d9438737bcecf97f3061e9872', 'accepted', NULL, NULL, '2026-05-12 14:20:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'admission_letter', 'admission_letter.pdf', 'private/applications/5/b156a4da-305f-4add-92b1-f3f377f7c5d2.pdf', 'application/pdf', 617, 'f97c5539179a62c39426463b2a6ead69c7f3660c0adafecced865ef12dcb31ba', 'under_review', NULL, NULL, NULL, NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00184'), 'id_copy', 'id_copy.jpg', 'private/applications/6/9efaf8fd-5c71-466a-9f76-e746c4b6fd7c.jpg', 'image/jpeg', 18960, '5275d7bdf4378e164df813eea0eebb8ed7d4b40da23f63af81183c5c6178ccd3', 'accepted', NULL, NULL, '2026-08-01 10:00:00.000', NULL),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00184'), 'certificate', 'certificate.pdf', 'private/applications/6/74dd39ed-af65-4514-9a49-3e3d00be4238.pdf', 'application/pdf', 610, 'a78d5643af1c5da9bfd1f747937633cb8f24c00bc679e28d057c2621875ce20a', 'under_review', NULL, NULL, NULL, NULL);

INSERT INTO application_events (application_id, type, actor_id, visible_to_applicant, data, created_at) VALUES
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00179\"}', '2026-02-10 09:15:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'DOCS_RECEIVED', NULL, 1, NULL, '2026-02-10 10:15:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00179'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"new\",\"to\":\"under_review\"}', '2026-02-11 09:15:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00180'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00180\"}', '2026-01-15 11:40:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00180'), 'DOCS_RECEIVED', NULL, 1, NULL, '2026-01-15 12:40:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00180'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"new\",\"to\":\"under_review\"}', '2026-01-17 11:40:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00180'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"under_review\",\"to\":\"rejected\"}', '2026-02-01 13:00:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00181'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00181\"}', '2026-09-20 16:05:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00182\"}', '2026-03-05 08:30:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'DOCS_RECEIVED', NULL, 1, NULL, '2026-03-05 09:30:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"new\",\"to\":\"under_review\"}', '2026-03-06 08:30:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'INTERVIEW_SCHEDULED', NULL, 1, NULL, '2026-03-08 08:30:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'INTERVIEW_BOOKED', NULL, 1, NULL, '2026-03-09 08:30:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00182'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"interview\",\"to\":\"accepted\"}', '2026-04-10 10:00:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00183\"}', '2026-05-12 14:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'DOCS_RECEIVED', NULL, 1, NULL, '2026-05-12 15:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"new\",\"to\":\"under_review\"}', '2026-05-13 14:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'DOCUMENT_REJECTED', NULL, 1, '{\"docType\":\"id_copy\",\"reason\":\"صورة الهوية غير واضحة\"}', '2026-05-13 20:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'DOCS_REQUESTED', NULL, 1, '{\"docTypes\":[\"id_copy\"]}', '2026-05-13 20:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00183'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"under_review\",\"to\":\"docs_missing\"}', '2026-05-13 20:20:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00184'), 'SUBMITTED', NULL, 1, '{\"reference\":\"SA-2026-00184\"}', '2026-08-01 10:00:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00184'), 'DOCS_RECEIVED', NULL, 1, NULL, '2026-08-01 11:00:00.000'),
  ((SELECT id FROM applications WHERE reference = 'SA-2026-00184'), 'STATUS_CHANGED', NULL, 1, '{\"from\":\"new\",\"to\":\"under_review\"}', '2026-08-02 10:00:00.000');

INSERT INTO interview_slots (starts_at, ends_at, location_ar, location_en, application_id) VALUES
  ('2026-03-09 08:30:00.000', '2026-03-09 09:30:00.000', 'مقر الجمعية — الرياض، حي السويدي', 'Association office — Riyadh, Al Suwaidi', (SELECT id FROM applications WHERE reference = 'SA-2026-00182'));

INSERT INTO counters (`key`, value) VALUES
  ('application:2026', 184);

